### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by ghost** [zemrys/Vertcoin-One-Click-Miner#1]
After installing OCM for Windows 10 x64 and running it the first time, a dialog box is presented to notify the user of what data should be entered on the next screen. This dialog box has a grammar error:

"...to store it's settings.."

"it's" should not have an apostrophe because it is not a contraction of "it is".  In other words, the sentence would not be written, "...to store it is settings..".  I have included a screen shot.

![vertcoin ocm grammar error](https://user-images.githubusercontent.com/35347061/34843584-75ceaebc-f6d4-11e7-9c03-f6523300f95c.png)

**Comment by zemrys** [comment]
You're posting to the wrong fork for the OCM, in the future please refer to [this page](https://github.com/vertcoin/One-Click-Miner/issues).
Anyway nice catch, this will be fixed in the next release.
